title: Kho media - Khu học mở
remote_theme: "jekyll/minima@7d91bb5"
description: Kho lưu trữ cả đống tài nguyên immersion cho các chương trình học ngôn ngữ của Khu học mở
author: duykhanh471

minima:
  skin: auto
  nav_pages:
    - media-recs/tieng-anh/index.md
    - media-recs/tieng-nhat/index.md
    - media-recs/tieng-viet/index.md
    - media-recs/tieng-trung/index.md